spring:
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/
  profiles:
    active: prod

mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 自定义参数配置
heathlink:
  #指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
  database: mysql
  #配置文件信息
  properties:
    #配置文件路径 默认路径resources下的文件
    path:
    #配置文件名称
    name: generator.properties
#代码生成器，配置信息

