spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1/ms_user
#    username: root
#    password: yunyun.15yun
    #oracle配置
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@121.36.46.229:1521:orcl
    username: ymjy
    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_security
#    username: sa
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/renren_security
#    username: postgres
#    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml

# 打印sql
logging:
  level:
    cn.healthlink.pratt.dao : debug

pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


# 自定义参数配置
heathlink:
  database:
    #mysql对应数据名 oracle对应模式名 mysql为数据库链接中的模式名(只作为生成文件名称的一部分)
    schema: ymjy
  #配置文件信息
  properties:
    #配置文件路径 默认路径resources下的文件
    path:
    #配置文件名称
    name: generator.properties
  #生成文件配置
  file:
    name: jiaoben
    #生成文件路径
    path: ./
    #文件压缩格式
    format: zip




