spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.5:3306/hbs
    #    url: jdbc:mysql://127.0.0.1:3306/doctor?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: mabin
    password: mabin123
    #oracle配置
#    driverClassName: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.10.10:1521:helowin
#    username: renren
#    password: 123456
    #SQLServer配置
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_security
#    username: sa
#    password: 123456
    #PostgreSQL配置
#    driverClassName: org.postgresql.Driver
#    url: jdbc:postgresql://192.168.10.10:5432/renren_security
#    username: postgres
#    password: 123456


# 自定义参数配置
heathlink:
  database:
    #指定数据库类型，可选值有【mysql、oracle、sqlserver、postgresql】
    type: oracle
    #mysql对应数据名 oracle对应模式名
    schema: YMJY
  #配置文件信息
  properties:
    #配置文件路径 默认路径resources下的文件
    path:
    #配置文件名称
    name: generator.properties
#代码生成器，配置信息

#生成文件配置
file:
  name: jiaoben
  #生成文件路径
  path: ./
  #文件压缩格式
  format: zip
